- name: Create AWS instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - backstage: "{{backstage_name | default(tag_prefix+'backstage')}}"
    - castle_gate: "{{castle_gate_name | default(tag_prefix+'castle-gate')}}"
    - courtyard: "{{courtyard_name | default(tag_prefix+'courtyard')}}"
    - kitchen_door: "{{kitchen_door_name | default(tag_prefix+'kitchen-door')}}"
    - vault: "{{vault_name | default(tag_prefix+'vault')}}"
    - watch_tower: "{{watch_tower_name | default(tag_prefix+'watch-tower')}}"
    - dbs_key: "{{dbs_key_name | default(key_name)}}"
  roles:
    - create_instance_sally
    - associate_sally
    - create_instance_dbs
    - associate_dbs
    - create_instance_mail
    - associate_mail
    - create_instance_backstage
    - associate_backstage
    - create_instance_workers
    - create_instance_webfront
    - associate_webfront
