---
# Create the EC2 VPC security groups will be created into.

- name: Create EC2 VPC
  local_action:
     module: ec2_vpc
     state: present
     cidr_block: {{vpc_cidr}}
     resource_tags: { "Name":"{{tag_prefix}}vpc" }
     region: "{{aws_region}}"
     wait: yes
  register: vpc_data

- set_fact:
    vpc_id: "{{vpc_data.vpc_id}}"

- name: Create subnet for database servers
  ec2_vpc_subnet:
    state: present
    region: "{{aws_region}}"
    vpc_id: {{vpc_id}}
    cidr: {{dbs_subnet_cidr}}
    resource_tags:
      Name: Database Subnet
  register: database_subnet

- name: Create subnet for web servers
  ec2_vpc_subnet:
    state: present
    region: "{{aws_region}}"
    vpc_id: {{vpc_id}}
    cidr: {{web_subnet_cidr}}
    resource_tags:
      Name: Web Subnet
  register: web_subnet

- lineinfile: "dest=group_vars/dynamic regexp='^vpc_id:' line='vpc_id: {{vpc_id}}'"

- lineinfile: "dest=group_vars/dynamic regexp='^web_subnet_id:' line='web_subnet_id: {{web_subnet.subnet_id}}'"
