---
- name: Create mail EC2 instance
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{watch_tower}}"
    instance_type: "{{instance_type}}"
    instance_profile_name: "{{watch_tower}}-profile"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    wait: yes
    user_data: "{{ lookup('template', '../templates/watch-tower-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{tag_prefix}}archi"
      profile: "mail"
    count_tag:
      prefix: "{{tag_prefix}}archi"
      profile: "mail"
    exact_count: 1
  register: mailers
