---
# http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomains

- name: Create 'ElasticSearch' domain
  local_action:
    module: command
      aws --region {{aws_region}} es create-elasticsearch-domain --domain-name {{es.domain}} --elasticsearch-version {{es.version}} --elasticsearch-cluster-config  '{{es.cluster_config | to_json }}' --ebs-options '{{es.ebs_options | to_json }}'  --access-policies '{{ es.access_policies | to_json }}'

