---

- name: Association of elastic ip address to web-front
  local_action:
     module: ec2_eip
     instance_id: "{{web_servers.instances[0].id}}"
     public_ip: "{{web_elastic_ip}}"
     region: "{{aws_region}}"
