---
- name: Create worker EC2 instance
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{courtyard_name}}"
    instance_type: "{{instance_type}}"
    instance_profile_name: "{{tag_prefix}}{{courtyard_name}}-profile"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    wait: yes
    user_data: "{{ lookup('template', '../templates/courtyard-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{tag_prefix}}archi"
      profile: "worker"
    count_tag:
      prefix: "{{tag_prefix}}archi"
      profile: "worker"
    exact_count: 1
  register: workers
