---
- name: Create monitoring EC2 instances
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{kitchen_door_name}}"
    instance_type: "t2.small"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    instance_profile_name: "{{tag_prefix}}kitchen-door-profile"
    volumes:
      - device_name: /dev/sda1
        volume_size: 16
        delete_on_termination: true
    wait: yes
    user_data: "{{ lookup('template', '../templates/kitchen-door-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{tag_prefix}}archi"
      profile: "dev"
    count_tag:
      prefix: "{{tag_prefix}}archi"
      profile: "dev"
    exact_count: 1
  register: dev_servers

- route53:
    command: create
    zone: "{{tag_prefix}}ec2.internal."
    record: "dev.{{tag_prefix}}ec2.internal."
    private_zone: yes
    type: A
    value: "{{dev_servers.instances[0].private_ip}}"
    overwrite: yes
