---
- name: Create 'vault' role
  local_action:
    module: command
      aws --region {{aws_region}} iam create-role --role-name {{vault}} --assume-role-policy-document "file://roles/createiamroles/files/assume-role-policy.json"

- name: Create 'vault' instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam create-instance-profile --instance-profile-name {{vault}}-profile

- name: Adding 'vault' role to instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam add-role-to-instance-profile --role-name {{vault}} --instance-profile-name {{vault}}-profile
