# Create an EC2 instance, configure it with the packages required
# to run a front-end web server and make an AMI out of it.

- include_vars: group_vars/dynamic

- include: sally_configure.yml
- include: sally_ami.yml
- include: sally_cleanup.yml

- include: dbs_configure.yml
- include: dbs_ami.yml
- include: dbs_cleanup.yml

- include: webfront_configure.yml
- include: webfront_ami.yml
- include: webfront_cleanup.yml
