# Create and configure an EC2 instance as a SSH-accessible sally port

- name: Create EC2 instance to setup sally port server
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{courtyard}}"
    instance_profile_name: "{{courtyard}}-profile"
    instance_type: t2.micro
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    user_data: "{{lookup('template', '../templates/sally-cloud-init-script.j2')}}"
    wait: yes
  register: sally_base

- set_fact:
    sally_base_device_id: "{{sally_base.instances[0].id}}"

# Turn on when debugging:
#- lineinfile: "dest=group_vars/dynamic regexp='^sally_base_device_id:' line='sally_base_device_id: {{sally_base.instances[0].id}}'"

- debug: msg="Connect to the ec2 instance with ssh -i ~/.ssh/{{key_name}} fedora@{{sally_base.instances[0].public_ip}}"
