---
# XXX use action: ec2_eip instead? What about "vpc" params?
# http://docs.ansible.com/ansible/ec2_eip_module.html

- name: Allocate an elastic IP for the web front
  local_action:
     module: command
       aws ec2 allocate-address --domain vpc
  register: elasticip

- set_fact:
    elastic_ip: "{{ elasticip.stdout }}"

- lineinfile: "dest=group_vars/dynamic regexp='^web_elastic_ip:' line='web_elastic_ip: {{elastic_ip.PublicIp}}'"

