---
# Requires Ansible v1.4 or higher

- name: allocate new elastic IPs for web servers
  ec2_eip:
    region: "{{aws_region}}"
    in_vpc: yes
  register: web_eip

- lineinfile: "dest=group_vars/dynamic regexp='^web_elastic_ip:' line='web_elastic_ip: {{web_eip.public_ip}}'"

- name: Allocate a new Elastic IP for the NAT Gateway
  ec2_eip:
    region: "{{aws_region}}"
    in_vpc: yes
  register: nat_eip

- lineinfile: "dest=group_vars/dynamic regexp='^nat_elastic_ip:' line='nat_elastic_ip: {{nat_eip.public_ip}}'"
