# Create and configure an EC2 instance as a base for web server AMIs.

- name: Create EC2 instance to setup front-end web server
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{courtyard}}"
    instance_profile_name: "{{courtyard}}-profile"
    instance_type: t2.micro
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    user_data: "{{lookup('template', '../templates/webfront-cloud-init-script.j2')}}"
    wait: yes
  register: webfront_base

- set_fact:
    webfront_base_device_id: "{{webfront_base.instances[0].id}}"

# Turn on when debugging:
#- lineinfile: "dest=group_vars/dynamic regexp='^webfront_base_device_id:' line='webfront_base_device_id: {{webfront_base.instances[0].id}}'"

# AMIs are created through the build bot in a security group
# that is not accessible from the public Internet.
- debug: msg="Connect to the ec2 instance with ssh -i ~/.ssh/{{key_name}} fedora@{{webfront_base.instances[0].private_dns_name}}"
