# Create and configure an EC2 instance as a base for web server AMIs.
#
# When there is more than one vpc, Ansible will fail with an error
# "groupId cannot be empty" when `vpc_subnet_id` is not specified.
# This also requires to add ec2:DescribeSubnets as Ansible will
# try to derive the VPC from the subnet (`vpc_id = vpc.get_all_subnets(
# subnet_ids=[vpc_subnet_id])[0].vpc_id`). Unfortunately there are no `vpc_id`
# option to module ec2.

- name: Create EC2 instance to setup front-end web server
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{courtyard}}"
    vpc_subnet_id: "{{web_subnet_id}}"
    instance_profile_name: "{{courtyard}}-profile"
    instance_type: t2.micro
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    user_data: "{{lookup('template', '../templates/webfront-cloud-init-script.j2')}}"
    wait: yes
  register: webfront_base

- set_fact:
    webfront_base_device_id: "{{webfront_base.instances[0].id}}"

# Writes the instance id so we can restart from the AMI creation phase in case
# the wait loop times out before the instance is fully configured.
- lineinfile: "dest=group_vars/dynamic regexp='^webfront_base_device_id:' line='webfront_base_device_id: {{webfront_base.instances[0].id}}'"
- lineinfile: "dest=group_vars/dynamic regexp='^webfront_base_private_dns_name:' line='webfront_base_device_id: {{webfront_base.instances[0].private_dns_name}}'"

# AMIs are created through the build bot in a security group
# that is not accessible from the public Internet.
- debug: msg="Connect to the ec2 instance with ssh -i ~/.ssh/{{key_name}} fedora@{{webfront_base.instances[0].private_dns_name}}"
