# Create the AMI.

- name: Wait for configuration of EC2 instance completed
  wait_for:
    delay: 540
    host: "{{webfront_base.instances[0].private_dns_name}}"
    port: 80
    state: started

- name: Register AMI for front-end web servers
  local_action:
    module: ec2_ami
    region: "{{aws_region}}"
    instance_id: "{{webfront_base_device_id}}"
    name: "webfront-{{webfront_base_device_id}}"
    description: "Front-end web reverse proxy"
    wait: yes
  register: webfront_ami

# Records the ami-id is the set of dynamic variables for other playbooks.
- lineinfile: "dest=group_vars/dynamic regexp='^webfront_ami_id:' line='webfront_ami_id: {{webfront_ami.image_id}}'"
