# Create the AMI.
#
# cloud-init has been timed at 10 min 20 sec, so we will wait 15min
# for the webserver to come up.

- name: Wait for configuration of EC2 instance completed
  wait_for:
    delay: 900
    host: "{{webfront_base_private_dns_name}}"
    port: 80
    state: started

- name: Register AMI for front-end web servers
  local_action:
    module: ec2_ami
    region: "{{aws_region}}"
    instance_id: "{{webfront_base_device_id}}"
    name: "webfront-{{webfront_base_device_id}}"
    description: "Front-end web reverse proxy"
    wait: yes
  register: webfront_ami

# Records the ami-id is the set of dynamic variables for other playbooks.
- lineinfile: "dest=group_vars/dynamic regexp='^webfront_ami_id:' line='webfront_ami_id: {{webfront_ami.image_id}}'"
