---

# XXX We need a ``value`` parameter which will require us
# to get the dynamic record.

#- route53:
#    command: delete
#    zone: "{{tag_prefix}}ec2.internal."
#    record: "web.{{tag_prefix}}ec2.internal."
#    private_zone: yes
#    type: A

#- route53:
#    command: delete
#    zone: "{{tag_prefix}}ec2.internal."
#    record: "dbs.{{tag_prefix}}ec2.internal."
#    private_zone: yes
#    type: A

#- route53:
#    command: delete
#    zone: "{{tag_prefix}}ec2.internal."
#    record: "dev.{{tag_prefix}}ec2.internal."
#    private_zone: yes
#    type: A

- name: Terminate EC2 instances using count_tag with exact_count of zero.
  local_action:
    module: ec2
    region: "{{aws_region}}"
    image: "{{ami_id}}"
    count_tag:
      prefix: "{{tag_prefix}}archi"
    exact_count: 0
