---
- name: Remove 'castle-gate' role from instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam remove-role-from-instance-profile --instance-profile-name {{castle_gate}}-profile --role-name {{castle_gate}}
  ignore_errors: True

- name: Delete 'castle-gate' role
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-role --role-name {{castle_gate}}
  ignore_errors: True

- name: Delete 'castle-gate' instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-instance-profile --instance-profile-name {{castle_gate}}-profile
  ignore_errors: True



