---
- name: Remove 'kitchen-door' role from instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam remove-role-from-instance-profile --instance-profile-name {{kitchen_door}}-profile --role-name {{kitchen_door}}
  ignore_errors: True

- name: Delete 'kitchen-door' role
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-role --role-name {{kitchen_door}}
  ignore_errors: True

- name: Delete 'kitchen-door' Instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-instance-profile --instance-profile-name {{kitchen_door}}-profile
  ignore_errors: True
