# Create VPC and Subnets

- include_vars: group_vars/dynamic

- name: Create EC2 VPC
  local_action:
     module: ec2_vpc_net
     state: present
     cidr_block: "{{vpc_cidr}}"
     name: "{{tag_prefix}}vpc"
     region: "{{aws_region}}"
  register: vpc_data

- set_fact:
    vpc_id: "{{vpc_data.vpc.id}}"

- lineinfile: "dest=group_vars/dynamic regexp='^vpc_id:' line='vpc_id: {{vpc_id}}'"

- name: Create subnet for database servers
  ec2_vpc_subnet:
    state: present
    region: "{{aws_region}}"
    vpc_id: "{{vpc_id}}"
    az: "{{aws_zone}}"
    cidr: "{{dbs_subnet_cidr}}"
    resource_tags: { "Name":"{{tag_prefix}} Database Subnet" }
  register: dbs_subnet

- set_fact:
    dbs_subnet_id: "{{dbs_subnet.subnet.id}}"

- lineinfile: "dest=group_vars/dynamic regexp='^dbs_subnet_id:' line='dbs_subnet_id: {{dbs_subnet_id}}'"

- name: Create subnet for web servers
  ec2_vpc_subnet:
    state: present
    region: "{{aws_region}}"
    vpc_id: "{{vpc_id}}"
    az: "{{aws_zone}}"
    cidr: "{{web_subnet_cidr}}"
    resource_tags: { "Name":"{{tag_prefix}} Web Subnet" }
  register: web_subnet

- set_fact:
    web_subnet_id: "{{web_subnet.subnet.id}}"

- lineinfile: "dest=group_vars/dynamic regexp='^web_subnet_id:' line='web_subnet_id: {{web_subnet_id}}'"
