# Release all resources acquired by running aws-create-authorized.yml

- name: Deleting groups and roles
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - deletegroups
    - deleteiamroles
    - deleteprivatedns
    - deletevpc
    - deleteelasticip
    - deletes3bucket
