---
- name: Remove 'courtyard' role from instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam remove-role-from-instance-profile --instance-profile-name {{courtyard}}-profile --role-name {{courtyard}}
  ignore_errors: True

- name: Delete 'courtyard' role
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-role --role-name {{courtyard}}
  ignore_errors: True

- name: Delete 'courtyard' Instance profile
  local_action:
    module: command
      aws --region {{aws_region}} iam delete-instance-profile --instance-profile-name {{courtyard}}-profile
  ignore_errors: True

